os: linux
language: go
go:
- 1.16.2
- tip
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
    - curl
script:
- ruby scripts/test.rb units
- make release
notifications:
  slack:
    secure: pN6VCJoPEp/PJ1rauiTP3wgrt5l+EcJeLi6/REkVKXVzkKVnLKhJvipQJ7i+FijMTIRw3+UXT1yBNe/Z0YbSSUenQDqy5rxfKyNyx0cfRaYRYj4xcCe6+jBNBC2SAohUWFeFiaK9uupd4zkTfeVCndqCj1I2y6V9iRGIWgm4Knx1QbclcCImqDAkMqZ2qDbP7k6jsUbfaMpnaPtXARfpmej3Vjr+tpsdqI0A05JgUg7DMhxM+42M5UuMwmLk2lQ8/C0LNGwipNi+bhPCbYobIfTCB+a1P7Z0KDDQYbo1Hmp9Pulh+0Sk35Rcer4djwZXO/zppjVe5/rXGZMubFyxwLDideF3vorQWbj6EdytDMdtHSe7cvyBWokr0vBwjubaHj25bMB5W1OSS8ymfTB6EJKplFyWEMnIov/E9VtagI2EUiuIxhjA4SHw7GHoLDauW0qtUUJcK80ChdAkT0IzZl6wT5d3t7pvCCqQ12ZMeC/zQz51lE55/KJxo2cd7/S2Gw8+iMH/+UJTN9uLsssxR5OjBUEW5t+0dUXTyLXXrf9GkDkos2TB/unIawMCskILM8yg62dNaXpDwjRP7bNgqSqZeUGiB4kPJujMGAE7PPsff7WTSUHmRyMS/XSqqxs17V4FNdivGCtVYewKIvbdvBO0aAF9TEiFJrY+H7nShSs=
branches:
  only:
  - "/.*/"
