---
version: '3.7'
x-aws-vpc: "vpc-4bd09e2c"
services:
   ingest_cleanup: &default
      image: aptrust/ingest_cleanup:c4dac87-master
      restart: always
      volumes:
        #- data:/app/data
        #- data:/app/logs
        - type: bind
          source: /Users/acr7d/logs # "${DOCKER_DATA_PATH:-./docker}"
          target: /app/data
        #- type: bind
        #  source: /Users/acr7d/logs # "${DOCKER_DATA_PATH:-./docker}"
        #  target: /app/logs
        #- type: bind
        #  source: ".env.docker"
        #  target: /app/.env
      env_file:
         - .env.docker
   ingest_bucket_reader:
      image: aptrust/ingest_bucket_reader:c4dac87-master
      restart: always
      <<: *default
   ingest_format_identifier:
      image: aptrust/ingest_format_identifier:c4dac87-master
      <<: *default
#   ingest_pre_fetch:
#      image: aptrust/ingest_pre_fetch:c2f095e-master
#      <<: *default
#   ingest_preservation_uploader:
#      image: aptrust/ingest_preservation_uploader:c2f095e-master
#      <<: *default
#   ingest_preservation_verifier:
#      image: aptrust/ingest_preservation_verifier:c2f095e-master
#      <<: *default
#   ingest_recorder:
#      image: aptrust/ingest_recorder:c2f095e-master
#      <<: *default
#   ingest_staging_uploader:
#      image: aptrust/ingest_staging_uploader:c2f095e-master
#      <<: *default
#   ingest_validator:
#      image: aptrust/ingest_validator:c2f095e-master
#      <<: *default
#   reingest_manager:
#      image: aptrust/reingest_manager:c2f095e-master
#      <<: *default
   apt_queue:
      image: aptrust/apt_queue:c2f095e-master
      <<: *default
   apt_queue_fixity:
      image: aptrust/apt_queue_fixity:c2f095e-master
      <<: *default
   apt_delete:
      image: aptrust/apt_delete:c2f095e-master
      <<: *default
   apt_fixity:
      image: aptrust/apt_fixity:c2f095e-master
      <<: *default
   bag_restorer:
      image: aptrust/bag_restorer:c2f095e-master
      <<: *default
   file_restorer:
      image: aptrust/file_restorer:c2f095e-master
      <<: *default
   glacier_restorer:
      image: aptrust/glacier_restorer:c2f095e-master
      <<: *default
volumes:
  data:
