// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NSQClientInterface is an autogenerated mock type for the NSQClientInterface type
type NSQClientInterface struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: topic, workItemId
func (_m *NSQClientInterface) Enqueue(topic string, workItemId int) error {
	ret := _m.Called(topic, workItemId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(topic, workItemId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
