// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PharosClientInterface is an autogenerated mock type for the PharosClientInterface type
type PharosClientInterface struct {
	mock.Mock
}
